/**
 * ATOM
 * ATOM project backned api specification
 *
 * OpenAPI spec version: 1.0.8
 * Contact: ilies.bourouh@groupehydrapharm.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommandModelLines } from './commandModelLines';

export interface CommandModel { 
    id?: string;
    createdAt?: string;
    paymentMethod?: CommandModel.PaymentMethodEnum;
    delivery?: CommandModel.DeliveryEnum;
    lines?: Array<CommandModelLines>;
}
export namespace CommandModel {
    export type PaymentMethodEnum = 'cash' | 'debt' | 'Epayment';
    export const PaymentMethodEnum = {
        Cash: 'cash' as PaymentMethodEnum,
        Debt: 'debt' as PaymentMethodEnum,
        Epayment: 'Epayment' as PaymentMethodEnum
    };
    export type DeliveryEnum = 'home' | 'pickup';
    export const DeliveryEnum = {
        Home: 'home' as DeliveryEnum,
        Pickup: 'pickup' as DeliveryEnum
    };
}